# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'RoadToRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RoadToRxSwift
  pod 'RxSwift', '~> 6.6.0' # <https://github.com/ReactiveX/RxSwift>
  pod 'RxCocoa', '~> 6.6.0'
  pod 'RxDataSources', '~> 5.0.0' # <https://github.com/RxSwiftCommunity/RxDataSources>
  pod 'RxSwiftExt', '~> 6.2.1' # <https://github.com/RxSwiftCommunity/RxSwiftExt>
  pod 'RxGesture', '~> 4.0.4' # <https://github.com/RxSwiftCommunity/RxGesture>
  pod 'Action'

  pod 'SwiftyJSON', '~> 5.0.1' # <https://github.com/SwiftyJSON/SwiftyJSON>
  pod 'SwifterSwift', '~> 6.0.0' # <https://github.com/SwifterSwift/SwifterSwift>

  # UI
  pod 'MBProgressHUD'
  pod 'MJRefresh'

  # 检测内存泄漏时，查看当前 RxSwift 申请的所有资源数量
  # 使用示例：print(RxSwift.Resources.total)
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'RxSwift'
              target.build_configurations.each do |config|
                  if config.name == 'Debug'
                      config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                  end
              end
          end
      end
  end

end
