# 指明依赖库的来源地址
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SwiftCheatSheet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftCheatSheet
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'
  pod 'IGListKit'
  pod 'SwifterSwift' # Extension扩展
  pod 'SwiftyBeaver' # 日志记录

end
