# 指明依赖库的来源地址
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SwiftCheatSheet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftCheatSheet
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'
  pod 'IGListKit'
  pod 'FaveButton'
  pod 'SwifterSwift', :git => 'https://github.com/SwifterSwift/SwifterSwift.git', :branch => 'master'

  # 服务
  pod 'SwiftyBeaver' # 日志记录
  pod 'SPPermissions/Camera' # 相机
  pod 'SPPermissions/PhotoLibrary' # 相册
  pod 'SPPermissions/Notification' # 通知
  pod 'SPPermissions/Microphone' # 麦克风
  pod 'SPPermissions/LocationWhenInUse' # 定位
  pod 'SPPermissions/LocationAlways'
  pod 'SPPermissions/Tracking' # 用户跟踪
end
