//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 5 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `AuteursBackground`.
    var auteursBackground: RswiftResources.ColorResource { .init(name: "AuteursBackground", path: [], bundle: bundle) }

    /// Color `rw-dark`.
    var rwDark: RswiftResources.ColorResource { .init(name: "rw-dark", path: [], bundle: bundle) }

    /// Color `rw-green`.
    var rwGreen: RswiftResources.ColorResource { .init(name: "rw-green", path: [], bundle: bundle) }

    /// Color `rw-light`.
    var rwLight: RswiftResources.ColorResource { .init(name: "rw-light", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 97 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `background`.
    var background: RswiftResources.ImageResource { .init(name: "background", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `background_Bayleaf`.
    var background_Bayleaf: RswiftResources.ImageResource { .init(name: "background_Bayleaf", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `blackKlansman`.
    var blackKlansman: RswiftResources.ImageResource { .init(name: "blackKlansman", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `blackKlansmanBig`.
    var blackKlansmanBig: RswiftResources.ImageResource { .init(name: "blackKlansmanBig", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `brightStar`.
    var brightStar: RswiftResources.ImageResource { .init(name: "brightStar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `budapestHotel`.
    var budapestHotel: RswiftResources.ImageResource { .init(name: "budapestHotel", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `candle`.
    var candle: RswiftResources.ImageResource { .init(name: "candle", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat`.
    var cat: RswiftResources.ImageResource { .init(name: "cat", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `confetti0`.
    var confetti0: RswiftResources.ImageResource { .init(name: "confetti0", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `confetti1`.
    var confetti1: RswiftResources.ImageResource { .init(name: "confetti1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `confetti2`.
    var confetti2: RswiftResources.ImageResource { .init(name: "confetti2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `confetti3`.
    var confetti3: RswiftResources.ImageResource { .init(name: "confetti3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `confetti4`.
    var confetti4: RswiftResources.ImageResource { .init(name: "confetti4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `confetti5`.
    var confetti5: RswiftResources.ImageResource { .init(name: "confetti5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `davidCronenberg`.
    var davidCronenberg: RswiftResources.ImageResource { .init(name: "davidCronenberg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `departed`.
    var departed: RswiftResources.ImageResource { .init(name: "departed", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `doTheRightThing`.
    var doTheRightThing: RswiftResources.ImageResource { .init(name: "doTheRightThing", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dribbble`.
    var dribbble: RswiftResources.ImageResource { .init(name: "dribbble", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `escapeNewYork`.
    var escapeNewYork: RswiftResources.ImageResource { .init(name: "escapeNewYork", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `estonia`.
    var estonia: RswiftResources.ImageResource { .init(name: "estonia", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `existenz`.
    var existenz: RswiftResources.ImageResource { .init(name: "existenz", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `feature-bg`.
    var featureBg: RswiftResources.ImageResource { .init(name: "feature-bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto1`.
    var fluidPhoto1: RswiftResources.ImageResource { .init(name: "fluidPhoto1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto10`.
    var fluidPhoto10: RswiftResources.ImageResource { .init(name: "fluidPhoto10", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto11`.
    var fluidPhoto11: RswiftResources.ImageResource { .init(name: "fluidPhoto11", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto12`.
    var fluidPhoto12: RswiftResources.ImageResource { .init(name: "fluidPhoto12", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto13`.
    var fluidPhoto13: RswiftResources.ImageResource { .init(name: "fluidPhoto13", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto14`.
    var fluidPhoto14: RswiftResources.ImageResource { .init(name: "fluidPhoto14", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto15`.
    var fluidPhoto15: RswiftResources.ImageResource { .init(name: "fluidPhoto15", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto16`.
    var fluidPhoto16: RswiftResources.ImageResource { .init(name: "fluidPhoto16", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto17`.
    var fluidPhoto17: RswiftResources.ImageResource { .init(name: "fluidPhoto17", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto18`.
    var fluidPhoto18: RswiftResources.ImageResource { .init(name: "fluidPhoto18", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto2`.
    var fluidPhoto2: RswiftResources.ImageResource { .init(name: "fluidPhoto2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto3`.
    var fluidPhoto3: RswiftResources.ImageResource { .init(name: "fluidPhoto3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto4`.
    var fluidPhoto4: RswiftResources.ImageResource { .init(name: "fluidPhoto4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto5`.
    var fluidPhoto5: RswiftResources.ImageResource { .init(name: "fluidPhoto5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto6`.
    var fluidPhoto6: RswiftResources.ImageResource { .init(name: "fluidPhoto6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto7`.
    var fluidPhoto7: RswiftResources.ImageResource { .init(name: "fluidPhoto7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto8`.
    var fluidPhoto8: RswiftResources.ImageResource { .init(name: "fluidPhoto8", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `fluidPhoto9`.
    var fluidPhoto9: RswiftResources.ImageResource { .init(name: "fluidPhoto9", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `france`.
    var france: RswiftResources.ImageResource { .init(name: "france", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `germany`.
    var germany: RswiftResources.ImageResource { .init(name: "germany", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ghost`.
    var ghost: RswiftResources.ImageResource { .init(name: "ghost", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `goodfellas`.
    var goodfellas: RswiftResources.ImageResource { .init(name: "goodfellas", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `halloween`.
    var halloween: RswiftResources.ImageResource { .init(name: "halloween", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `hat`.
    var hat: RswiftResources.ImageResource { .init(name: "hat", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `holySmoke`.
    var holySmoke: RswiftResources.ImageResource { .init(name: "holySmoke", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_backpack`.
    var ic_backpack: RswiftResources.ImageResource { .init(name: "ic_backpack", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_book`.
    var ic_book: RswiftResources.ImageResource { .init(name: "ic_book", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_camera`.
    var ic_camera: RswiftResources.ImageResource { .init(name: "ic_camera", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_coffee`.
    var ic_coffee: RswiftResources.ImageResource { .init(name: "ic_coffee", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_glasses`.
    var ic_glasses: RswiftResources.ImageResource { .init(name: "ic_glasses", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_ice_cream`.
    var ic_ice_cream: RswiftResources.ImageResource { .init(name: "ic_ice_cream", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_smoking_pipe`.
    var ic_smoking_pipe: RswiftResources.ImageResource { .init(name: "ic_smoking_pipe", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_vespa`.
    var ic_vespa: RswiftResources.ImageResource { .init(name: "ic_vespa", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `inTheCut`.
    var inTheCut: RswiftResources.ImageResource { .init(name: "inTheCut", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ireland`.
    var ireland: RswiftResources.ImageResource { .init(name: "ireland", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `italy`.
    var italy: RswiftResources.ImageResource { .init(name: "italy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `janeCampion`.
    var janeCampion: RswiftResources.ImageResource { .init(name: "janeCampion", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `johnCarpenter`.
    var johnCarpenter: RswiftResources.ImageResource { .init(name: "johnCarpenter", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `jungleFever`.
    var jungleFever: RswiftResources.ImageResource { .init(name: "jungleFever", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `kanagawa`.
    var kanagawa: RswiftResources.ImageResource { .init(name: "kanagawa", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lifeAquatic`.
    var lifeAquatic: RswiftResources.ImageResource { .init(name: "lifeAquatic", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `malcomX`.
    var malcomX: RswiftResources.ImageResource { .init(name: "malcomX", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `martinScorsese`.
    var martinScorsese: RswiftResources.ImageResource { .init(name: "martinScorsese", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mascot_swifty-birthday-party`.
    var mascot_swiftyBirthdayParty: RswiftResources.ImageResource { .init(name: "mascot_swifty-birthday-party", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `monaco`.
    var monaco: RswiftResources.ImageResource { .init(name: "monaco", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `nigeria`.
    var nigeria: RswiftResources.ImageResource { .init(name: "nigeria", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `overlay`.
    var overlay: RswiftResources.ImageResource { .init(name: "overlay", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `owl`.
    var owl: RswiftResources.ImageResource { .init(name: "owl", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pause`.
    var pause: RswiftResources.ImageResource { .init(name: "pause", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `play`.
    var play: RswiftResources.ImageResource { .init(name: "play", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `poland`.
    var poland: RswiftResources.ImageResource { .init(name: "poland", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pot`.
    var pot: RswiftResources.ImageResource { .init(name: "pot", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pumkin`.
    var pumkin: RswiftResources.ImageResource { .init(name: "pumkin", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ragingBull`.
    var ragingBull: RswiftResources.ImageResource { .init(name: "ragingBull", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rip`.
    var rip: RswiftResources.ImageResource { .init(name: "rip", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `royalTenenbaums`.
    var royalTenenbaums: RswiftResources.ImageResource { .init(name: "royalTenenbaums", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rushmore`.
    var rushmore: RswiftResources.ImageResource { .init(name: "rushmore", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `russia`.
    var russia: RswiftResources.ImageResource { .init(name: "russia", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rwdevcon-bg`.
    var rwdevconBg: RswiftResources.ImageResource { .init(name: "rwdevcon-bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `scanners`.
    var scanners: RswiftResources.ImageResource { .init(name: "scanners", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `se-icon`.
    var seIcon: RswiftResources.ImageResource { .init(name: "se-icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `skull`.
    var skull: RswiftResources.ImageResource { .init(name: "skull", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sky`.
    var sky: RswiftResources.ImageResource { .init(name: "sky", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `spain`.
    var spain: RswiftResources.ImageResource { .init(name: "spain", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `spikeLee`.
    var spikeLee: RswiftResources.ImageResource { .init(name: "spikeLee", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `taxiDriver`.
    var taxiDriver: RswiftResources.ImageResource { .init(name: "taxiDriver", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `theFly`.
    var theFly: RswiftResources.ImageResource { .init(name: "theFly", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `thePiano`.
    var thePiano: RswiftResources.ImageResource { .init(name: "thePiano", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `theThing`.
    var theThing: RswiftResources.ImageResource { .init(name: "theThing", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `theyLive`.
    var theyLive: RswiftResources.ImageResource { .init(name: "theyLive", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `toxic`.
    var toxic: RswiftResources.ImageResource { .init(name: "toxic", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `uk`.
    var uk: RswiftResources.ImageResource { .init(name: "uk", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `us`.
    var us: RswiftResources.ImageResource { .init(name: "us", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `videodrome`.
    var videodrome: RswiftResources.ImageResource { .init(name: "videodrome", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `wesAnderson`.
    var wesAnderson: RswiftResources.ImageResource { .init(name: "wesAnderson", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
            var uiSceneStoryboardFile: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneStoryboardFile") ?? "Main" }
          }
        }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 3 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `albums.json`.
    var albumsJson: RswiftResources.FileResource { .init(name: "albums", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `content.json`.
    var contentJson: RswiftResources.FileResource { .init(name: "content", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `homepage.json`.
    var homepageJson: RswiftResources.FileResource { .init(name: "homepage", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 25 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `ActionCell`.
    var actionCell: RswiftResources.NibReference<ActionCell> { .init(name: "ActionCell", bundle: bundle) }

    /// Nib `AdCell`.
    var adCell: RswiftResources.NibReference<AdCell> { .init(name: "AdCell", bundle: bundle) }

    /// Nib `BirdSoundTableViewCell`.
    var birdSoundTableViewCell: RswiftResources.NibReference<BirdSoundTableViewCell> { .init(name: "BirdSoundTableViewCell", bundle: bundle) }

    /// Nib `BlueLibraryViewController`.
    var blueLibraryViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "BlueLibraryViewController", bundle: bundle) }

    /// Nib `CommentCell`.
    var commentCell: RswiftResources.NibReference<CommentCell> { .init(name: "CommentCell", bundle: bundle) }

    /// Nib `CornerRadiusTableViewCell`.
    var cornerRadiusTableViewCell: RswiftResources.NibReference<CornerRadiusTableViewCell> { .init(name: "CornerRadiusTableViewCell", bundle: bundle) }

    /// Nib `CustomTableViewCell`.
    var customTableViewCell: RswiftResources.NibReference<CustomTableViewCell> { .init(name: "CustomTableViewCell", bundle: bundle) }

    /// Nib `FSPageViewController`.
    var fsPageViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "FSPageViewController", bundle: bundle) }

    /// Nib `GameViewController`.
    var gameViewController: RswiftResources.NibReference<GameView> { .init(name: "GameViewController", bundle: bundle) }

    /// Nib `IconCollectionViewCell`.
    var iconCollectionViewCell: RswiftResources.NibReference<IconCollectionViewCell> { .init(name: "IconCollectionViewCell", bundle: bundle) }

    /// Nib `ImageCell`.
    var imageCell: RswiftResources.NibReference<ImageCell> { .init(name: "ImageCell", bundle: bundle) }

    /// Nib `MergeVideoViewController`.
    var mergeVideoViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MergeVideoViewController", bundle: bundle) }

    /// Nib `ModeratorTableViewCell`.
    var moderatorTableViewCell: RswiftResources.NibReference<ModeratorTableViewCell> { .init(name: "ModeratorTableViewCell", bundle: bundle) }

    /// Nib `ModeratorsSearchViewController`.
    var moderatorsSearchViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ModeratorsSearchViewController", bundle: bundle) }

    /// Nib `MultipleSelectionViewController`.
    var multipleSelectionViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MultipleSelectionViewController", bundle: bundle) }

    /// Nib `PhotoDetailViewController`.
    var photoDetailViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PhotoDetailViewController", bundle: bundle) }

    /// Nib `PhotoListTableViewCell`.
    var photoListTableViewCell: RswiftResources.NibReference<PhotoListTableViewCell> { .init(name: "PhotoListTableViewCell", bundle: bundle) }

    /// Nib `PickerViewController`.
    var pickerViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PickerViewController", bundle: bundle) }

    /// Nib `PlayVideoViewController`.
    var playVideoViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PlayVideoViewController", bundle: bundle) }

    /// Nib `PlayerViewController`.
    var playerViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PlayerViewController", bundle: bundle) }

    /// Nib `RealnameCell`.
    var realnameCell: RswiftResources.NibReference<RealnameCell> { .init(name: "RealnameCell", bundle: bundle) }

    /// Nib `RecordVideoViewController`.
    var recordVideoViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "RecordVideoViewController", bundle: bundle) }

    /// Nib `SuperHeroNameCell`.
    var superHeroNameCell: RswiftResources.NibReference<SuperHeroNameCell> { .init(name: "SuperHeroNameCell", bundle: bundle) }

    /// Nib `UserCell`.
    var userCell: RswiftResources.NibReference<UserCell> { .init(name: "UserCell", bundle: bundle) }

    /// Nib `VideoNinjaViewController`.
    var videoNinjaViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "VideoNinjaViewController", bundle: bundle) }

    func validate() throws {
      if UIKit.UIImage(named: "play", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'play' is used in nib 'BirdSoundTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "se-icon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'se-icon' is used in nib 'ModeratorsSearchViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "mascot_swifty-birthday-party", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'mascot_swifty-birthday-party' is used in nib 'PickerViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "rw-dark", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'rw-dark' is used in nib 'PickerViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "rw-green", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'rw-green' is used in nib 'PickerViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "rw-dark", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'rw-dark' is used in nib 'PlayerViewController', but couldn't be loaded.") }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {
        if UIKit.UIImage(named: "rwdevcon-bg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'rwdevcon-bg' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UINavigationController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}