platform :ios, '12.0'
use_frameworks!

def my_pods
  pod 'RxSwift'
  pod 'SwiftyJSON'
  pod 'Gifu'
  pod 'SwiftyGif'
end

target 'iGif' do
  my_pods
end

target 'iGifTests' do
  my_pods
  pod 'Nimble'
  pod 'RxNimble'
  pod 'RxBlocking'
  pod 'OHHTTPStubs/Swift'
end
